# Generated by Django 2.1.7 on 2019-11-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20191127_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='number',
            field=models.TextField(),
        ),
    ]
