# Generated by Django 2.1.7 on 2019-11-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20191127_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='category',
            new_name='newTitle',
        ),
        migrations.RemoveField(
            model_name='server',
            name='keyword',
        ),
        migrations.AlterField(
            model_name='server',
            name='number',
            field=models.IntegerField(),
        ),
    ]
