# Generated by Django 2.1.7 on 2019-11-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20191128_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
