# Generated by Django 2.1.7 on 2019-12-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20191130_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='number',
            field=models.IntegerField(max_length=50),
        ),
    ]
